[package]
name = "mutant-protocol"
version = "0.6.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
base64 = "0.21"
thiserror = "1.0"
