[package]
name = "mutant-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
mutant-client = { path = "../mutant-client" }
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.2", features = ["derive"] }
colored = "2.0"
uuid = "1.16.0"
