name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Run Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings

    - name: Make test script executable
      run: chmod +x scripts/run_tests_with_env.sh

    - name: Install procps (for pgrep)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y procps

    - name: Run tests with environment script
      run: ./scripts/run_tests_with_env.sh 